services:
  api:
    container_name: dj_ambassador_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - dj_ambassador_db
    #command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
  dj_ambassador_db:
    container_name: dj_ambassador_db
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54322:5432