# Generated by Django 5.1.3 on 2025-03-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.link'),
        ),
    ]
