# Generated by Django 5.1.3 on 2025-04-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='core.link'),
        ),
    ]
